#!/bin/sh -e
#
# ap start
sudo /home/pi/openpibo-os/system/wifi-ap-sta run

# 복구 usb
if [ -f /media/usb/_index.py ]; then
  sudo python3 /media/usb/_index.py
  exit 0
fi

# Amp init
sudo gpio mode 7 out
sudo gpio write 7 1

# pir on
echo "#30:on!" > /dev/ttyS0

sudo amixer -c Headphones sset Headphone 75%
sudo play /home/pi/openpibo-os/system/opening.mp3 reverb &

# network init
sudo python3 /home/pi/openpibo-os/system/booting.py

# run ide
cd /home/pi/openpibo-os/ide;sudo node main.js &

# run openpibo-tools
cd /home/pi/openpibo-os/tools;sudo python3 main.py &

sudo iw wlan0 set power_save off
sudo iw ap0 set power_save off
exit 0
