#!/bin/sh -e
#
# recovery usb
if [ -f /media/usb/update.zip ]; then
  sudo unzip /media/usb/update.zip -d /home/pi/
  sudo bash /home/pi/_update
  exit 0
fi

# hostname management
rpi_serial=$(grep "Serial" /proc/cpuinfo | awk '{print $3}' | rev | cut -c -8 | rev)
if [ $rpi_serial != "$(hostname)" ]
then
  sudo hostnamectl set-hostname --static ${rpi_serial}
  echo "127.0.0.1 localhost" > /etc/hosts
  echo "::1       localhost ip6-localhost ip6-loopback" >> /etc/hosts
  echo "ff02::1   ip6-allnodes" >> /etc/hosts
  echo "ff02::2   ip6-allrouters" >> /etc/hosts
  echo "127.0.0.1 ${rpi_serial}" >> /etc/hosts
  sudo shutdown -r now
fi

mkdir -p /home/pi/code
mkdir -p /home/pi/myimage
mkdir -p /home/pi/myaudio
mkdir -p /home/pi/mymodel

# ap start
sudo /home/pi/openpibo-os/system/wifi-ap-sta start

# network init
cd /home/pi/openpibo-os/system;sudo /home/pi/.pyenv/bin/python3 booting.py &

# run server
#cd /home/pi/openpibo-os/ide;sudo node main.js &
cd /home/pi/openpibo-os/ide;sudo /home/pi/.pyenv/bin/python3 main.py &
cd /home/pi/openpibo-os/tools;sudo /home/pi/.pyenv/bin/python3 main.py &

# motor init
servo init

# ap start
#sudo /home/pi/openpibo-os/system/wifi-ap-sta run

# Amp init
sudo gpio mode 7 out
sudo gpio write 7 1

# pir on
#echo "#30:on!" > /dev/ttyS0

#sudo iw wlan0 set power_save off
#sudo iw ap0 set power_save off
exit 0
